//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easy_Stock
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clientes()
        {
            this.Deudas_Clientes = new HashSet<Deudas_Clientes>();
            this.Facturas = new HashSet<Facturas>();
            this.Remitos = new HashSet<Remitos>();
            this.Transacciones = new HashSet<Transacciones>();
        }
    
        public int idCliente { get; set; }
        public Nullable<int> idTipoCliente { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public string direccion { get; set; }
        public Nullable<int> idLocalidad { get; set; }
        public Nullable<int> idProvincia { get; set; }
        public string codigoPostal { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
        public Nullable<int> idSexo { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string dni { get; set; }
        public Nullable<int> idTipoEmpresa { get; set; }
        public string razonSocial { get; set; }
        public string barrio { get; set; }
        public string cuit { get; set; }
        public Nullable<bool> habilitado { get; set; }
    
        public virtual Sexos Sexos { get; set; }
        public virtual Localidades Localidades { get; set; }
        public virtual Provincias Provincias { get; set; }
        public virtual Tipos_Clientes Tipos_Clientes { get; set; }
        public virtual Tipos_Empresas Tipos_Empresas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deudas_Clientes> Deudas_Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facturas> Facturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Remitos> Remitos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transacciones> Transacciones { get; set; }
    }
}
