//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easy_Stock
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalles_Facturas
    {
        public int idDetalle { get; set; }
        public int nroFactura { get; set; }
        public int cantidad { get; set; }
        public int idProducto { get; set; }
        public Nullable<int> iva { get; set; }
        public decimal subTotal { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<int> idInventario { get; set; }
    
        public virtual Facturas Facturas { get; set; }
        public virtual Inventario Inventario { get; set; }
    }
}
