//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easy_Stock
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deudas_Clientes
    {
        public int idDeuda { get; set; }
        public decimal monto { get; set; }
        public Nullable<int> idCliente { get; set; }
        public Nullable<decimal> montoAfavor { get; set; }
    
        public virtual Clientes Clientes { get; set; }
    }
}
