//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easy_Stock
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Facturas()
        {
            this.Detalles_Facturas = new HashSet<Detalles_Facturas>();
        }
    
        public int nroFactura { get; set; }
        public System.DateTime fecha { get; set; }
        public decimal total { get; set; }
        public string observaciones { get; set; }
        public int idEmpresa { get; set; }
        public int idCliente { get; set; }
        public int idFormaPago { get; set; }
        public int idUsuario { get; set; }
        public Nullable<int> idTransaccion { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalles_Facturas> Detalles_Facturas { get; set; }
        public virtual Empresas Empresas { get; set; }
        public virtual Formas_Pago Formas_Pago { get; set; }
        public virtual Transacciones Transacciones { get; set; }
    }
}
