//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easy_Stock
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inventario()
        {
            this.Detalles_Facturas = new HashSet<Detalles_Facturas>();
        }
    
        public int idInventario { get; set; }
        public string codigo { get; set; }
        public int idProducto { get; set; }
        public Nullable<int> idEstado { get; set; }
        public Nullable<int> idTransaccion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalles_Facturas> Detalles_Facturas { get; set; }
        public virtual Estados_Productos Estados_Productos { get; set; }
        public virtual Productos Productos { get; set; }
        public virtual Transacciones Transacciones { get; set; }
    }
}
