//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easy_Stock
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Productos()
        {
            this.Detalles_Pedidos = new HashSet<Detalles_Pedidos>();
            this.Detalles_Remitos = new HashSet<Detalles_Remitos>();
            this.Inventario = new HashSet<Inventario>();
            this.LotesxProductos = new HashSet<LotesxProductos>();
        }
    
        public int idProducto { get; set; }
        public string codigo { get; set; }
        public string nombre { get; set; }
        public Nullable<int> idMarca { get; set; }
        public decimal precioVenta { get; set; }
        public decimal precioCosto { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> idCategoria { get; set; }
        public Nullable<int> idProveedor { get; set; }
        public Nullable<int> idDeposito { get; set; }
        public int stockMinimo { get; set; }
        public int stockMaximo { get; set; }
        public Nullable<int> cantidadRestante { get; set; }
        public Nullable<System.DateTime> fechaVenc { get; set; }
        public Nullable<System.DateTime> fechaElab { get; set; }
        public Nullable<bool> habilitado { get; set; }
        public Nullable<System.DateTime> fechaIngreso { get; set; }
    
        public virtual Categorias Categorias { get; set; }
        public virtual Depositos Depositos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalles_Pedidos> Detalles_Pedidos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalles_Remitos> Detalles_Remitos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventario> Inventario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LotesxProductos> LotesxProductos { get; set; }
        public virtual Marcas Marcas { get; set; }
        public virtual Productos Productos1 { get; set; }
        public virtual Productos Productos2 { get; set; }
        public virtual Proveedores Proveedores { get; set; }
    }
}
