//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easy_Stock
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remitos
    {
        public int idRemito { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<int> idFormaPago { get; set; }
        public Nullable<int> idCliente { get; set; }
        public decimal total { get; set; }
        public Nullable<decimal> descuento { get; set; }
        public Nullable<decimal> recargo { get; set; }
        public Nullable<decimal> iva { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Formas_Pago Formas_Pago { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
