//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easy_Stock
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transacciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transacciones()
        {
            this.Facturas = new HashSet<Facturas>();
            this.Inventario = new HashSet<Inventario>();
            this.Transacciones_x_Transacciones = new HashSet<Transacciones_x_Transacciones>();
            this.Transacciones_x_Transacciones1 = new HashSet<Transacciones_x_Transacciones>();
        }
    
        public int idTransaccion { get; set; }
        public System.DateTime fecha { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> idCliente { get; set; }
        public Nullable<int> idProveedor { get; set; }
        public Nullable<float> descuento { get; set; }
        public Nullable<float> total { get; set; }
        public Nullable<int> idFormaPago { get; set; }
        public Nullable<int> idTipoTransaccion { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<bool> devuelto { get; set; }
        public Nullable<int> idTipoDevolucion { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facturas> Facturas { get; set; }
        public virtual Formas_Pago Formas_Pago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventario> Inventario { get; set; }
        public virtual Proveedores Proveedores { get; set; }
        public virtual Tipos_Devoluciones Tipos_Devoluciones { get; set; }
        public virtual Tipos_Transacciones Tipos_Transacciones { get; set; }
        public virtual Transacciones Transacciones1 { get; set; }
        public virtual Transacciones Transacciones2 { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transacciones_x_Transacciones> Transacciones_x_Transacciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transacciones_x_Transacciones> Transacciones_x_Transacciones1 { get; set; }
    }
}
