//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easy_Stock
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transacciones_x_Transacciones
    {
        public int id { get; set; }
        public Nullable<int> idTransaccionMadre { get; set; }
        public Nullable<int> idTransaccionHija { get; set; }
    
        public virtual Transacciones Transacciones { get; set; }
        public virtual Transacciones Transacciones1 { get; set; }
    }
}
